# Generated by Django 6.1.1 on 2026-09-10 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('faith', 'Faith'), ('purpose', 'Purpose'), ('leadership', 'Leadership'), ('youth', 'Youth'), ('discipleship', 'Discipleship'), ('prayer', 'Prayer'), ('christian-living', 'Christian Living')], max_length=32)),
                ('excerpt', models.TextField(max_length=400)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='articles/')),
                ('image_fallback', models.CharField(blank=True, help_text='Filename in static/ministry/images/', max_length=120)),
                ('published_at', models.DateField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('general', 'General Enquiry'), ('speaking', 'Speaking Invitation'), ('partnership', 'Ministry Partnership'), ('testimony', 'Testimony'), ('prayer', 'Prayer Request')], max_length=24)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('youth', 'Youth Gathering'), ('church', 'Church Service'), ('leadership', 'Leadership Event'), ('ministry', 'Ministry Meeting'), ('special', 'Special Event')], max_length=24)),
                ('starts_at', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('registration_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('preached_on', models.DateField(default=django.utils.timezone.now)),
                ('youtube_video_id', models.CharField(blank=True, help_text='YouTube video ID for embed, e.g. dQw4w9WgXcQ', max_length=32)),
                ('thumbnail', models.ImageField(blank=True, upload_to='messages/')),
                ('thumbnail_fallback', models.CharField(blank=True, max_length=120)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-preached_on'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scripture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_text', models.TextField()),
                ('reference', models.CharField(max_length=80)),
                ('theme', models.CharField(choices=[('calling', 'Calling'), ('purpose', 'Purpose'), ('faith', 'Faith'), ('evangelism', 'Evangelism'), ('discipleship', 'Discipleship'), ('courage', 'Courage'), ('generation', 'Next Generation'), ('witness', 'Witness')], default='faith', max_length=24)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_name', models.CharField(default='David Sudher Ministries', max_length=120)),
                ('tagline', models.CharField(default='Raising a generation to know Christ and make Christ known.', max_length=200)),
                ('youtube_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('other_url', models.URLField(blank=True, help_text='Optional additional platform')),
                ('other_label', models.CharField(blank=True, max_length=40)),
                ('youtube_channel_id', models.CharField(blank=True, help_text='For future dynamic YouTube imports', max_length=80)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, help_text='Official David Sudher Ministries logo. Do not replace with a generated mark.', upload_to='branding/')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('story', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='testimonies/')),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonies',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TodaysWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('title', models.CharField(default="Today's Word", max_length=160)),
                ('thought', models.TextField()),
                ('verse_text', models.TextField()),
                ('verse_reference', models.CharField(max_length=80)),
                ('encouragement', models.TextField(blank=True)),
                ('prayer', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Today's Word",
                'verbose_name_plural': "Today's Words",
                'ordering': ['-date'],
            },
        ),
    ]
